#!/bin/bash
echo $(for sar in $(find /var/log/sysstat -type f | egrep -i '(bz|xz)'); do xzcat $sar | sar -r -f ; done | grep Average | tr -s ' ' | cut -d " " -f7 | awk '{ total += $1 } END { print total/NR/1024 }' ; for sar in $(find /var/log/sysstat -type f | egrep -i '(bz|xz)'); do xzcat $sar | sar -r -f ; done | grep Average | tr -s ' ' | cut -d " " -f7 | awk '{ total += $1 } END { print total/NR/1024 }') | tr ' ' '\n' | sort -nr | head -n 1 ;\
echo $(for sar in $(find /var/log/sysstat -type f | egrep -i '(bz|xz)'); do xzcat $sar | sar -r -f ; done | egrep -vi '(Average|kbcommit|Linux)' | tr -s ' ' | cut -d " " -f8 | sort -nr | head -n1 | awk '{ total += $1 } END { print total/NR/1024 }' ; for sar in $(find /var/log/sysstat -type f | egrep -vi '(sar|bz|xz)'); do sar -r -f $sar; done | egrep -vi '(Average|kbcommit|Linux)' | tr -s ' ' | cut -d " " -f8 | sort -nr | head -n1 | awk '{ total += $1 } END { print total/NR/1024 }') | tr ' ' '\n' | sort -nr | head -n 1 ;\
echo $(for sar in $(find /var/log/sysstat -type f | egrep -i '(bz|xz)' ); do xzcat $sar | sar -q -f ; done | grep Average | tr -s ' ' | cut -d " " -f4 | awk '{ total += $1 } END { print total/NR }' ; for sar in $(find /var/log/sysstat -type f | egrep -vi '(sar|bz|xz)' ); do sar -q -f $sar; done | grep Average | tr -s ' ' | cut -d " " -f4 | awk '{ total += $1 } END { print total/NR }') | tr ' ' '\n' | sort -nr | head -n 1 ;\
echo $(for sar in $(find /var/log/sysstat -type f | egrep -i '(bz|xz)' ); do xzcat $sar | sar -q -f ; done | egrep -vi '(Average|blocked|Linux)' | tr -s " " | cut -d " " -f5 | sort -nr | head -n1 | awk '{ total += $1 } END { print total/NR }' ; for sar in $(find /var/log/sysstat -type f | egrep -vi '(sar|bz|xz)' ); do sar -q -f $sar; done | egrep -vi '(Average|blocked|Linux)' | tr -s " " | cut -d " " -f5 | sort -nr | head -n1 | awk '{ total += $1 } END { print total/NR }') | tr ' ' '\n' | sort -nr | head -n 1 ;\
echo $(df -B 1073741824 | tr -s ' ' |  egrep -vi '(Available|shm|tmpfs|udev|:)' | cut -d " " -f2-99 | grep -vi "/dev/" | cut -d " " -f1 | tr '\n' ' ' | tr ' ' '+' | sed 's/.$//') | bc ;\
echo $(df -B 1073741824 | tr -s ' ' |  egrep -vi '(Available|shm|tmpfs|udev|:)' | cut -d " " -f2-99 | grep -vi "/dev/" | cut -d " " -f3 | tr '\n' ' ' | tr ' ' '+' | sed 's/.$//') | bc ;


for sar in $(find /var/log/sysstat -type f | egrep -vi '(sar|bz|xz)'); do sar -r -f $sar; done | grep Average | tr -s ' ' | cut -d " " -f7 | awk '{ total += $1 } END { print total/NR/1024 }' ;\
for sar in $(find /var/log/sysstat -type f | egrep -vi '(sar|bz|xz)'); do sar -r -f $sar; done | egrep -vi '(Average|kbcommit|Linux)' | tr -s ' ' | cut -d " " -f8 | sort -nr | head -n1 | awk '{ total += $1 } END { print total/NR/1024 }' ;\
for sar in $(find /var/log/sysstat -type f | egrep -vi '(sar|bz|xz)' ); do sar -q -f $sar; done | grep Average | tr -s ' ' | cut -d " " -f4 | awk '{ total += $1 } END { print total/NR }' ;\
for sar in $(find /var/log/sysstat -type f | egrep -vi '(sar|bz|xz)' ); do sar -q -f $sar; done | egrep -vi '(Average|blocked|Linux)' | tr -s " " | cut -d " " -f5 | sort -nr | head -n1 | awk '{ total += $1 } END { print total/NR }' ;\
echo $(df -B 1073741824 | tr -s ' ' |  egrep -vi '(Available|shm|tmpfs|udev|:)' | cut -d " " -f2-99 | grep -vi "/dev/" | cut -d " " -f1 | tr '\n' ' ' | tr ' ' '+' | sed 's/.$//') | bc ;\
echo $(df -B 1073741824 | tr -s ' ' |  egrep -vi '(Available|shm|tmpfs|udev|:)' | cut -d " " -f2-99 | grep -vi "/dev/" | cut -d " " -f3 | tr '\n' ' ' | tr ' ' '+' | sed 's/.$//') | bc ;
